/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.myfirstapp;

// importations
import java.awt.Component;
import javax.swing.JOptionPane;
/**
 *
 * @author RONALD TCHUEKOU
 */
public class dataRanges extends javax.swing.JFrame {


    /* 
        Les données recuperer ici sont les suivantes: 
        -> Code de la matiere
        -> Code de la filiere
        -> Nom des profs
    */
    private String codeMatiere;
    private String codeFiliere;
    private String nameProfs;


    // Génération des setter.
    public void setCodeMatiere(String codeMatiere){
        this.codeMatiere = codeMatiere;
    }

    public void setCodeFiliere(String codeFiliere){
        this.codeFiliere = codeFiliere;
    }

    public void setNameProfs(String nameProfs){
        this.nameProfs = nameProfs;
    }

    /**
    * Fonction qui permet de convertir les donees de cette classe en json.
    */
    private void convertToJson(){
        
    }


    /**
     * Creates new form dataRanges.
     */
    public dataRanges() {
        initComponents();
        initFrameText();

        this.codeMatiere = "";
        this.codeFiliere = "";
        this.nameProfs = "";
    }
    
    /**
     * Fonction qui permet d'initialiser les champs.
     */
    private void initFrameText(){
        JTCodeMatiere.setText(this.codeMatiere);
        JTFiliere.setText(this.codeFiliere);
        JTProf.setText(this.nameProfs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        JTCodeMatiere = new javax.swing.JTextField();
        JTFiliere = new javax.swing.JTextField();
        JTProf = new javax.swing.JTextField();
        ValidData = new javax.swing.JButton();
        cancelData = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saisie des données de la plage");
        setLocation(new java.awt.Point(550, 250));
        setName("dataRange"); // NOI18N
        setPreferredSize(new java.awt.Dimension(250, 250));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 250));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(153, 153, 255));
        label1.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 0, 102));
        label1.setText("Données de la plage");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JTCodeMatiere.setName("CMatiere"); // NOI18N
        JTCodeMatiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTCodeMatiereMouseClicked(evt);
            }
        });

        JTFiliere.setName("CFiliere"); // NOI18N

        JTProf.setName("Nprof"); // NOI18N

        ValidData.setIcon(new javax.swing.ImageIcon("C:\\Users\\GENERAL STORE\\Documents\\NetBeansProjects\\myFirstApp\\src\\main\\java\\com\\mycompany\\myfirstapp\\icons\\success.png")); // NOI18N
        ValidData.setText("Valider");
        ValidData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ValidData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidDataActionPerformed(evt);
            }
        });

        cancelData.setIcon(new javax.swing.ImageIcon("C:\\Users\\GENERAL STORE\\Documents\\NetBeansProjects\\myFirstApp\\src\\main\\java\\com\\mycompany\\myfirstapp\\icons\\error.png")); // NOI18N
        cancelData.setText("Annuler");
        cancelData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDataActionPerformed(evt);
            }
        });

        jLabel1.setText("Code matière :");

        jLabel2.setText("Code filière :");

        jLabel3.setText("Nom Profs :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(result)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JTCodeMatiere)
                                .addComponent(JTFiliere)
                                .addComponent(JTProf, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                            .addComponent(ValidData, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTCodeMatiere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFiliere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(2, 2, 2)
                .addComponent(result)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelData)
                    .addComponent(ValidData))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDataActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelDataActionPerformed

    private void JTCodeMatiereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTCodeMatiereMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCodeMatiereMouseClicked

    private void ValidDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidDataActionPerformed
        // Récuperation des données entrer.
        this.codeMatiere = JTCodeMatiere.getText();
        this.codeFiliere = JTFiliere.getText();
        this.nameProfs = JTProf.getText();
        
        this.showMessage("Code matiere: "+ codeMatiere + ", code filiere: "+ codeFiliere + "Nom profs: "+ nameProfs);
        this.setVisible(false);
    }//GEN-LAST:event_ValidDataActionPerformed
    
    /**
     * Fonction qui retourne tous les valeurs entrées sous forme de chaine.
     * @return String value.
     */
    public String getAllValue (){
        return "{"
                + "\"codeMatier\":\""+codeMatiere+"\","
                + "\"codeFiliere\":\""+codeFiliere+"\","
                + "\"nomProfs\":\""+nameProfs+"\""
                + "}";
    }
    
    /**
     * Fonction qui permet d'afficher une boite de dialogue à l'utilisateur.
     */
    private void showMessage(String message){
        Component frame = this;
        JOptionPane.showMessageDialog(frame, message);
    }

    // Fonction qui permet de rentrer a la page de création des programmes de salles.
    private void showFrameHome(){
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataRanges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataRanges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataRanges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataRanges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataRanges().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTCodeMatiere;
    private javax.swing.JTextField JTFiliere;
    private javax.swing.JTextField JTProf;
    private javax.swing.JButton ValidData;
    private javax.swing.JButton cancelData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables
}
